-- ==============================================================================
-- NASHWA ("THE PATH TO GROWTH") - SUPABASE DATABASE SCHEMA & INITIAL SEED DATA
-- ==============================================================================
-- Instructions:
-- 1. Open your Supabase Project Dashboard (https://supabase.com/dashboard)
-- 2. Click on "SQL Editor" in the left navigation sidebar
-- 3. Click "New Query", paste this entire script, and click "RUN" (or Ctrl+Enter)
-- ==============================================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. DROP EXISTING TABLES (IF RESETTING)
DROP TABLE IF EXISTS public.orders CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.shops CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.courses CASCADE;
DROP TABLE IF EXISTS public.events CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- 3. PROFILES TABLE (Linked with Supabase Auth auth.users)
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT,
  email TEXT UNIQUE,
  role TEXT DEFAULT 'customer',
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW())
);

-- 4. CATEGORIES TABLE
CREATE TABLE public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT,
  icon TEXT,
  image TEXT,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW())
);

-- 5. SHOPS TABLE (Artisan Guilds & Workshops)
CREATE TABLE public.shops (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT,
  rating NUMERIC(3, 2) DEFAULT 5.0,
  banner TEXT,
  logo TEXT,
  location TEXT,
  owner_name TEXT,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW())
);

-- 6. PRODUCTS TABLE
CREATE TABLE public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC(10, 2) NOT NULL,
  original_price NUMERIC(10, 2),
  rating NUMERIC(3, 2) DEFAULT 5.0,
  reviews_count INTEGER DEFAULT 0,
  image TEXT,
  category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
  shop_id BIGINT REFERENCES public.shops(id) ON DELETE SET NULL,
  in_stock BOOLEAN DEFAULT TRUE,
  tags TEXT,
  is_featured BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW())
);

-- 7. UNIVERSITY COURSES TABLE
CREATE TABLE public.courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  instructor TEXT NOT NULL,
  duration TEXT NOT NULL,
  level TEXT NOT NULL,
  rating NUMERIC(3, 2) DEFAULT 5.0,
  price NUMERIC(10, 2) NOT NULL,
  image TEXT,
  category TEXT,
  students_count INTEGER DEFAULT 0,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW())
);

-- 8. FEASTS & EVENTS TABLE
CREATE TABLE public.events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  date TEXT NOT NULL,
  location TEXT NOT NULL,
  price NUMERIC(10, 2) NOT NULL,
  image TEXT,
  category TEXT,
  capacity INTEGER DEFAULT 50,
  enrolled_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW())
);

-- 9. ORDERS TABLE
CREATE TABLE public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  customer_name TEXT NOT NULL,
  customer_email TEXT NOT NULL,
  address TEXT NOT NULL,
  city TEXT NOT NULL,
  items_json JSONB NOT NULL,
  total_amount NUMERIC(10, 2) NOT NULL,
  status TEXT DEFAULT 'confirmed',
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW())
);

-- ==============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ==============================================================================
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shops ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Public Read Policies (Allow anyone to view products, categories, shops, courses, events)
CREATE POLICY "Allow public read access for categories" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Allow public read access for shops" ON public.shops FOR SELECT USING (true);
CREATE POLICY "Allow public read access for products" ON public.products FOR SELECT USING (true);
CREATE POLICY "Allow public read access for courses" ON public.courses FOR SELECT USING (true);
CREATE POLICY "Allow public read access for events" ON public.events FOR SELECT USING (true);

-- Orders Policies (Allow users to insert orders & read their own orders)
CREATE POLICY "Allow anonymous and authenticated order creation" ON public.orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow users to view their own orders" ON public.orders FOR SELECT USING (
  auth.uid() = user_id OR auth.role() = 'service_role' OR user_id IS NULL
);

-- Profiles Policies
CREATE POLICY "Allow individual read of own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Allow individual update of own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- ==============================================================================
-- AUTOMATIC PROFILE CREATION TRIGGER ON SUPABASE AUTH SIGNUP
-- ==============================================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, email, role)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'name', new.raw_user_meta_data->>'full_name', 'Customer'),
    new.email,
    'customer'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ==============================================================================
-- SEED DATA
-- ==============================================================================

-- 1. Categories
INSERT INTO public.categories (id, name, slug, description, icon, image) VALUES
(1, 'Artisan Crafts', 'artisan-crafts', 'Handcrafted pottery, leather goods, and intricate metalwork forged by master artisans.', 'sparkles', 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=800&q=80'),
(2, 'Botanical & Wellness', 'botanical-wellness', 'Pure essential oils, traditional herbal apothecary, and soothing organic soaps.', 'leaf', 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=800&q=80'),
(3, 'Organic Pantry', 'organic-pantry', 'Heritage spices, wild mountain honey, and small-batch cold-pressed oils.', 'coffee', 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=800&q=80'),
(4, 'Books & Wisdom', 'books-wisdom', 'Handbound journals, classical poetry, calligraphy tools, and philosophy prints.', 'book-open', 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80'),
(5, 'Feasts & Gastronomy', 'feasts-gastronomy', 'Traditional cookware, hammered brass teapots, and communal feast essentials.', 'utensils', 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80')
ON CONFLICT (id) DO NOTHING;

-- 2. Shops
INSERT INTO public.shops (id, name, slug, description, rating, banner, logo, location, owner_name) VALUES
(1, 'Al-Bazaar Botanicals', 'al-bazaar-botanicals', 'Hand-distilled essential oils and botanical skincare rooted in ancestral recipes.', 4.90, 'https://images.unsplash.com/photo-1512290900672-1f416e9196d4?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=200&q=80', 'Marrakech & Global Shipping', 'Fatima Noor'),
(2, 'Damascus Forge & Leather', 'damascus-forge-leather', 'Full-grain vegetable-tanned leather goods and hand-hammered brass coffee vessels.', 4.95, 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=200&q=80', 'Old Damascus Quarter', 'Tarek Al-Masri'),
(3, 'Atlas Terracotta Studio', 'atlas-terracotta-studio', 'Sculptural and functional ceramics made with sun-dried mountain clay.', 4.88, 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=200&q=80', 'Fez Medina', 'Yasmin Cherif'),
(4, 'Silk & Saffron Guild', 'silk-saffron-guild', 'Heritage super-grade saffron and masterfully hand-spun raw silk tapestries.', 4.92, 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=200&q=80', 'Kashmir Valley', 'Harun Qureshi'),
(5, 'Al-Hikmah Press & Bindery', 'al-hikmah-press', 'Preserving the art of hand-stitched archival paper, leather journals, and inkcraft.', 4.97, 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=200&q=80', 'Cairo Historic District', 'Dr. Zayd Mansour')
ON CONFLICT (id) DO NOTHING;

-- 3. Products
INSERT INTO public.products (id, name, description, price, original_price, rating, reviews_count, image, category_id, shop_id, in_stock, tags, is_featured) VALUES
(1, 'Royal Moroccan Amber Oud Oil', 'Aged 12 years with organic amber resin and wild agarwood notes. Deep, warm, and lingering.', 68.00, 85.00, 4.95, 84, 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=800&q=80', 2, 1, true, 'Fragrance, Luxury, Handcrafted', true),
(2, 'Hand-Hammered Damascus Brass Teapot', 'Pure solid brass kettle engraved with geometric Arabesque flourishes. Built to last generations.', 120.00, 145.00, 4.90, 52, 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80', 5, 2, true, 'Feasts, Brass, Tableware', true),
(3, 'Atlas Terracotta Serving Platter', 'Hand-thrown mountain clay platter with food-safe botanical white glaze. Ideal for feast banquets.', 54.00, 65.00, 4.85, 39, 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80', 1, 3, true, 'Ceramics, Kitchen, Artisan', true),
(4, 'Heritage Grade Negi Saffron (5g Tin)', 'Highest potency crimson stigma threads harvested by hand at dawn in Kashmir Valley.', 48.00, 60.00, 4.98, 112, 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=800&q=80', 3, 4, true, 'Organic, Gourmet, Spices', true),
(5, 'Hand-Stitched Full Grain Leather Journal', '240 pages of heavy cotton rag archival paper bound in vegetable-tanned distressed saddle leather.', 42.00, 50.00, 4.92, 67, 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80', 4, 5, true, 'Journal, Leather, Stationery', true),
(6, 'Wild Mountain Sidr Honey (500g)', 'Raw, unpasteurized monofloral honey harvested from high-altitude desert Sidr blossoms.', 36.00, 45.00, 4.94, 94, 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80', 3, 4, true, 'Honey, Organic, Pantry', false),
(7, 'Natural Olive & Laurel Aleppo Soap Bar', 'Cold-cured for nine months with 40% laurel berry oil. Rich in restorative minerals.', 14.00, 18.00, 4.88, 140, 'https://images.unsplash.com/photo-1607006310458-204a1122a7f0?auto=format&fit=crop&w=800&q=80', 2, 1, true, 'Bath, Soap, Organic', false),
(8, 'Traditional Carved Wood Spice Pestle', 'Sculpted from sustainably reclaimed olive wood with rich contrast grain and heavy grip.', 38.00, 48.00, 4.82, 28, 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=800&q=80', 1, 3, true, 'Woodcraft, Kitchen, Handcarved', false),
(9, 'Ancient Inkstone & Bamboo Quill Set', 'Hand-carved slate stone with traditional charcoal ink stick and three precision bamboo nibs.', 45.00, 55.00, 4.87, 31, 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=800&q=80', 4, 5, true, 'Calligraphy, Art, Wisdom', false),
(10, 'Zellige Pattern Ceramic Tea Tumblers (Set of 4)', 'Double-walled hand-painted ceramic tumblers that retain heat without burning fingers.', 58.00, 72.00, 4.91, 46, 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80', 5, 3, true, 'Tea, Ceramics, Gift', false)
ON CONFLICT (id) DO NOTHING;

-- 4. Courses
INSERT INTO public.courses (id, title, instructor, duration, level, rating, price, image, category, students_count, description) VALUES
(1, 'The Art of Natural Perfumery & Botanical Scent Blending', 'Fatima Noor (Master Distiller)', '6 Weeks (Self-paced + Live Labs)', 'All Levels', 4.96, 89.00, 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=800&q=80', 'Botanical Wisdom', 420, 'Learn ancient distillation techniques, pyramid scent architecture, resin extraction, and formulate your own signature eau de parfum.'),
(2, 'Artisan Business Mastery: From Workshop to Global Brand', 'Tarek Al-Masri & Guest Mentors', '8 Weeks', 'Intermediate', 4.93, 120.00, 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80', 'Entrepreneurship', 615, 'Pricing handmade goods, global logistics, supply transparency, brand storytelling, and scaling without sacrificing soulful craftsmanship.'),
(3, 'Heritage Ceramics: Clay Sourcing, Throwing & Earth Glazes', 'Yasmin Cherif (Ceramist)', '4 Weeks', 'Beginner to Intermediate', 4.90, 75.00, 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=800&q=80', 'Traditional Craft', 310, 'Master wheel throwing, pinch technique, natural slip creation, and wood-fired kiln science.'),
(4, 'Culinary Storytelling: The Ancient Spice Routes & Feasting Traditions', 'Chef Harun Qureshi', '5 Weeks', 'All Levels', 4.98, 65.00, 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=800&q=80', 'Gastronomy', 540, 'Unlock flavor layering, historical saffron and cardamom pairings, bread fermentation, and host meaningful communal feasts.')
ON CONFLICT (id) DO NOTHING;

-- 5. Events
INSERT INTO public.events (id, title, description, date, location, price, image, category, capacity, enrolled_count) VALUES
(1, 'Autumn Solstice Feast & Live Oud Night', 'A 5-course seasonal dinner curated by heritage chefs, paired with acoustic live Oud performances in an open-air courtyard.', 'Saturday, Oct 24, 2026 • 7:00 PM', 'Nashwa Andalusian Courtyard', 55.00, 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80', 'Feast & Music', 60, 48),
(2, 'Medina Artisan Night Souk & Exhibition', 'Meet 30+ master craftsmen, witness live glassblowing and carpet weaving, and enjoy spiced mint tea under the stars.', 'Friday, Nov 12, 2026 • 6:00 PM', 'Historic Medina Pavilion', 0.00, 'https://images.unsplash.com/photo-1512290900672-1f416e9196d4?auto=format&fit=crop&w=800&q=80', 'Community Souk', 200, 142),
(3, 'Scent-Blending & Botanical Distillation Workshop', 'An intimate, hands-on masterclass where every attendee distills orange blossoms and creates a bespoke 30ml scent to keep.', 'Sunday, Nov 28, 2026 • 2:00 PM', 'The Botanical Glasshouse', 70.00, 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=800&q=80', 'Workshop', 25, 19),
(4, 'Wild Sourdough & Clay Hearth Baking Experience', 'Learn slow fermentation using ancient grain flours and bake wood-fired loaves in our traditional outdoor stone oven.', 'Saturday, Dec 05, 2026 • 10:00 AM', 'Heritage Kitchen Farmhouse', 45.00, 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80', 'Culinary Craft', 30, 22)
ON CONFLICT (id) DO NOTHING;

-- Reset identity sequences
SELECT setval('categories_id_seq', (SELECT MAX(id) FROM categories));
SELECT setval('shops_id_seq', (SELECT MAX(id) FROM shops));
SELECT setval('products_id_seq', (SELECT MAX(id) FROM products));
SELECT setval('courses_id_seq', (SELECT MAX(id) FROM courses));
SELECT setval('events_id_seq', (SELECT MAX(id) FROM events));
